{
 "title": "sandbox",
 "tags": [ "sandbox" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_host",
    "label": "Node Host",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of time Series",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(prometheus_tsdb_head_series[1d])"
    }
   ]
  },
  {
   "title": "Bytes per Sample",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[1d]) / rate(prometheus_tsdb_compaction_chunk_samples_sum[1d])"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu, mode)(rate(node_cpu_seconds_total{instance=~\"$node_host\", job=\"node_exporter\"}[1m]))",
     "legendFormat": "{{instance}} : {{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "((1.296*10^6) * irate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[1m]) * (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[1d]) / rate(prometheus_tsdb_compaction_chunk_samples_sum[1d]))) / 10^9"
    }
   ]
  }
 ]
}