---
- hosts: local
  become: true
  vars_files:
    - /etc/ansible/group_vars/prometheus.vars.yml

  tasks:
    
  - name: Creating prometheus user group
    group: name="{{groupId}}"
    become: true
  
  - name: Creating prometheus user
    user:
      name: "{{userId}}"
      group: "{{groupId}}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{userId}} nologin User"
      createhome: "no"
      state: present
  
  - name: Install prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes
  
  - name: Copy prometheus file to bin
    copy:
      src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
      dest: "/usr/local/bin/prometheus"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755
  
  - name: Creates directory
    file: 
      path: "/var/lib/prometheus/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
  
  - name: Creates directory
    file: 
      path: "/etc/prometheus/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
  
  - name: Copy prometheus console file to /etc/prometheus
    copy:
      src: "/tmp/prometheus-{{ version }}.linux-amd64/{{ item }}"
      dest: "/etc/prometheus"
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
    with_items:
      ['consoles', 'console_libraries']

  - name: Delete prometheus tmp folder
    file:
      path: '/tmp/prometheus-{{ version }}.linux-amd64'
      state: absent

  - name: config file
    template:
      src: prometheus.conf.j2
      dest: /etc/prometheus/prometheus.yml

  - name: set prometheus as the owner of these files
    shell: chown prometheus. /usr/local/bin/prometheus /etc/prometheus/prometheus.yml /var/lib/prometheus/ /etc/prometheus/consoles /etc/prometheus/
 
  - name: Copy systemd init file
    template:
      src: init.service_prom.j2
      dest: /etc/systemd/system/prometheus.service
    notify: systemd_reload
  
  - name: Start prometheus service
    service:
      name: prometheus
      state: started
      enabled: yes
  
  - name: Check if prometheus is accessible
    uri:
      url: http://localhost:9090
      method: GET
      status_code: 200

- hosts: local
  become: true
  vars_files: 
    - /etc/ansible/group_vars/grafana.vars.yml

  tasks:

  - name: get grafana
    get_url:
      url: "https://dl.grafana.com/oss/release/grafana-{{ version }}.x86_64.rpm"
      dest: /tmp/
      checksum: sha256:125cea2958d9fe8db69c96f92bb0f7cb1ace1e5b09023f69608d86160d165c3e

  - name: Install grafana
    yum:
       name: /tmp/grafana-{{ version }}.x86_64.rpm
       state: present
    notify: 
      - systemd_reload
      - event_restart_grafana

  - name: enable grafana
    service:
      name: grafana-server
      enabled: yes
