---
- hosts: all
  become: true
  vars_files:
    - prometheus.vars.yml

  tasks:
    
  - name: Creating prometheus user group
    group: name="{{groupId}}"
    become: true
  
  - name: Creating prometheus user
    user:
      name: "{{userId}}"
      group: "{{groupId}}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{userId}} nologin User"
      createhome: "no"
      state: present
  
  - name: Install prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes
  
  - name: Copy prometheus file to bin
    copy:
      src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
      dest: "/usr/local/bin/prometheus"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755
  
  - name: Delete prometheus tmp folder
    file:
      path: '/tmp/prometheus-{{ version }}.linux-amd64'
      state: absent
  
  - name: config file
    template:
      src: prometheus.conf.j2
      dest: /etc/prometheus/prometheus.conf
  
  - name: Copy systemd init file
    template:
      src: init.service_prom.j2
      dest: /etc/systemd/system/prometheus.service
    notify: systemd_reload
  
  - name: Start prometheus service
    service:
      name: prometheus
      state: started
      enabled: yes
  
   - name: Check if prometheus is accessible
    uri:
      url: http://localhost:9090
      method: GET
      status_code: 200

- hosts: all
  become: true
  vars_files:
    - node_exporter.vars.yml

  tasks:

  - name: Creating node_exporter user group
    group: name="{{groupId}}"
    become: true

  - name: Creating node_exporter user
    user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

  - name: Install prometheus node exporter
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes

  - name: Copy prometheus node exporter file to bin
    copy:
      src: "/tmp/node_exporter-{{ version }}.linux-amd64/node_exporter"
      dest: "/usr/local/bin/node_exporter"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755

  - name: Delete node exporter tmp folder
    file:
      path: '/tmp/node_exporter-{{ version }}.linux-amd64'
      state: absent
      
  - name: Copy systemd init file
    template:
      src: init.service_node.j2
      dest: /etc/systemd/system/node_exporter.service

  - name: Start node_exporter service
    service:
      name: node_exporter
      state: started
      enabled: yes

  - name: Check if node exporter emits metrics
    uri:
      url: http://127.0.0.1:9100/metrics
      method: GET
      status_code: 200
