- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: systemd_reload
  command: systemctl daemon-reload
  listen: systemd_reload
