---
- hosts: apache
  become: true

  tasks:

  - name: Creating apache_exporter user group
    group: name="{{groupId}}"
    become: true

  - name: Creating apache_exporter user
    user:
      name: "{{userId}}"
      group: "{{groupId}}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{userId}} nologin User"
      createhome: "no"
      state: present

  - name: Install prometheus apache exporter
    unarchive:
      src: "https://github.com/Lusitaniae/apache_exporter/releases/download/v{{version}}/apache_exporter-{{version}}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes

  - name: Copy prometheus apache exporter file to bin
    copy:
      src: "/tmp/apache_exporter-{{ version }}.linux-amd64/apache_exporter"
      dest: "/usr/local/bin/apache_exporter"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755

  - name: Delete apache exporter tmp folder
    file:
      path: '/tmp/apache_exporter-{{ version }}.linux-amd64'
      state: absent
      
  - name: Copy systemd init file
    template:
      src: ../templates/init.service_node.j2
      dest: /etc/systemd/system/apache_exporter.service

  - name: Start apache_exporter service
    service:
      name: apache_exporter
      state: started
      enabled: yes

  - name: Enable the server status on apache
    blockinfile:
      path: /etc/httpd/conf/httpd.conf
      block: |
        <IfModule mod_status.c>
             ExtendedStatus On
           <Location /server-status>
             SetHandler server-status
             Allow from all
          </Location>
        </IfModule>

  - name: restart httpd service
    service:
      name: httpd
      state: restarted

  - name: Check if node exporter emits metrics
    uri:
      url: http://127.0.0.1:9117/metrics
      method: GET
      status_code: 200
