---
- hosts: prometheus
  become: yes

  tasks:
  - name: check if prometheus.service config file exist
    stat:
      path: /etc/systemd/system/prometheus.service
    register: result
  - debug:
      var: result

  - name: check if prometheus.service config has changed
    template:
      src: ../templates/init.service_prom.j2
      dest: /etc/systemd/system/prometheus.service
    register: template
    when: result.stat.exists == True

  - debug:
      var: template

  - name: restart systemd
    command: systemctl daemon-reload
    when: template.changed == true

