---
- hosts: prometheus
  become: true
  vars_files:
    - /etc/ansible/group_vars/alertmanager.vars.yml

  tasks:
  
  - name: Creating alertmanager user group
    group: name="{{groupId}}"
    become: true

  - name: Creating alertmanager user
    user:
      name: "{{userId}}"
      group: "{{groupId}}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{userId}} nologin User"
      createhome: "no"
      state: present

  - name: Install alertmanager
    unarchive:
      src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes

  - name: Creates directory
    file:
      path: "/var/lib/alertmanager/data"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755

  - name: Creates directory
    file:
      path: "/etc/alertmanager/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755

  - name: Copy alertmanager file to bin
    copy:
      src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
      dest: "/usr/local/bin/alertmanager"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755

  - name: Delete alertmanager tmp folder
    file:
      path: '/tmp/alertmanager-{{ version }}.linux-amd64'
      state: absent

  - name: config file
    template:
      src: ../templates/alertmanager.conf.j2
      dest: /etc/alertmanager/alertmanager.yml

  - name: Copy systemd init file
    template:
      src: ../templates/init.service_alertmanager.j2
      dest: /etc/systemd/system/alertmanager.service
    notify: systemd_reload

  - name: set alertmanager as the owner of these files
    command: chown alertmanager. /usr/local/bin/alertmanager /etc/alertmanager/alertmanager.yml

  - name: Started alertmanager service
    service:
      name: prometheus
      state: restarted
      enabled: yes

  - name: waiting for the service restart
    pause:
      seconds: 15

  - name: Check if alertmanager is accessible
    uri:
      url: http://localhost:9093
      method: GET
      status_code: 200
  

  handlers:
    - name: systemd_reload
      command: systemctl daemon-reload

- hosts: prometheus
  become: true
  vars_files:
    - /etc/ansible/group_vars/prometheus.vars.yml

  tasks:
    
  - name: Creating prometheus user group
    group: name="{{groupId}}"
    become: true
  
  - name: Creating prometheus user
    user:
      name: "{{userId}}"
      group: "{{groupId}}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{userId}} nologin User"
      createhome: "no"
      state: present
  
  - name: Install prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes
  
  - name: Copy prometheus file to bin
    copy:
      src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
      dest: "/usr/local/bin/prometheus"
      owner: "{{userId}}"
      group: "{{groupId}}"
      remote_src: yes
      mode: 0755
  
  - name: Creates directory
    file: 
      path: "/var/lib/prometheus/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
  
  - name: Creates directory
    file: 
      path: "/etc/prometheus/"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
  
  - name: Creates rules directory
    file: 
      path: "/etc/prometheus/rules"
      state: directory
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
  
  - name: Copy prometheus console file to /etc/prometheus
    copy:
      src: "/tmp/prometheus-{{ version }}.linux-amd64/{{ item }}"
      dest: "/etc/prometheus"
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
    with_items:
      ['consoles', 'console_libraries']

  - name: Delete prometheus tmp folder
    file:
      path: '/tmp/prometheus-{{ version }}.linux-amd64'
      state: absent

  - name: config file
    template:
      src: ../templates/prometheus.conf.j2
      dest: /etc/prometheus/prometheus.yml

  - name: set prometheus as the owner of these files
    shell: chown prometheus. /usr/local/bin/prometheus /etc/prometheus/prometheus.yml /var/lib/prometheus/ /etc/prometheus/consoles /etc/prometheus/

  - debug:
      var: playbook_dir

  - name: Copy up.rule file
    copy:
      src: "{{playbook_dir}}/rules/"
      dest: "/etc/prometheus/rules"
      owner: "{{userId}}"
      group: "{{groupId}}"
      mode: 0755
 
  - name: Copy systemd init file
    template:
      src: ../templates/init.service_prom.j2
      dest: /etc/systemd/system/prometheus.service
    notify: systemd_reload
  
  - name: Start prometheus service
    service:
      name: prometheus
      state: restarted
      enabled: yes

  - name: waiting for the service restart
    pause:
      seconds: 15
  
  - name: Check if prometheus is accessible
    uri:
      url: http://localhost:9090
      method: GET
      status_code: 200

- hosts: prometheus
  become: true
  vars_files: 
    - /etc/ansible/group_vars/grafana.vars.yml

  tasks:

  - name: get grafana
    get_url:
      url: "https://dl.grafana.com/oss/release/grafana-{{ version }}.x86_64.rpm"
      dest: /tmp/
      checksum: sha256:125cea2958d9fe8db69c96f92bb0f7cb1ace1e5b09023f69608d86160d165c3e

  - name: Install grafana
    yum:
       name: /tmp/grafana-{{ version }}.x86_64.rpm
       state: present
    notify: 
      - systemd_reload
      - event_restart_grafana

  - name: enable grafana
    service:
      name: grafana-server
      enabled: yes

